= README

== Building the project

[source, bash]
--
gradlew --no-daemon clean build <1>
--
<1> Due to https://github.com/jbake-org/jbake-gradle-plugin/issues/14[issue-14] the Gradle daemon has to be disabled. This should be fixed with JBake 2.5.

=== Using live preview

To watch file modifications run `gradlew -t build`. For serving the site content run `gradlew jettyRun` and the site will be available from http://localhost:8080[`http://localhost:8080`].

=== Publish to GitHub Pages

[source, bash]
--
gradlew --no-daemon publishGhPages  <1>
--
<1> Due to https://github.com/jbake-org/jbake-gradle-plugin/issues/14[issue-14] the Gradle daemon has to be disabled. This should be fixed with JBake 2.5.

== Adding Content

The preferrend content markup is AsciiDoc with the file extension `.adoc` (This is essential so GitHub can natively display those files).

=== Asciidoctor

http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#links[AsciiDoc Syntax Quick Reference]

http://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual]

http://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Writer’s Guide]

=== JBake

The site is managed by JBake. For organizing posts and pages it is neccessary to adhere to a few http://jbake.org/[JBake conventions].
